---
abstract: 'tiny object system with privacy settings for properties and methods, abstract classes and methods'
author:
  - 'Georgy Bazhukov <gosha@bugov.net>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.112621'
keywords:
  - Class
  - Object
  - Method
  - OOP
  - Private
  - Protected
  - Abstract
  - Interface
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pony-Object
provides:
  Pony::Object:
    file: lib/Pony/Object.pm
    version: 0.06
  Pony::Object::Throwable:
    file: lib/Pony/Object.pm
    version: 0
requires:
  Carp: 0
  Module::Load: 0
  Scalar::Util: 0
  Storable: 0
  perl: 5.010
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/h15/pony-object
version: 0.06
